apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: sjinaongkan-eks
  region: us-east-1

nodeGroups:
  - name: ng-1
    instanceType: t3.micro
    desiredCapacity: 1
    volumeSize: 80
    # sget sh:
    #   allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
availabilityzones: ['us-east-1a', 'us-east-1b']

